config/routes.rb
Rails.application.routes.draw do
  resources :attempts
  resources :subgenres
  resources :questions
  resources :genres
  resources :destroys
  resources :users 
 # get 'admin/index'

  #get 'sessions/new'
  #root 'welcome#index'
  get 'sessions/create'

  get 'sessions/destroy'

  

  get 'admin' => 'admin#index'

  get 'homepage' => 'play#homepage'

  controller :sessions do
  	get 'login' => :new
  	post 'login' => :create
  	get 'logout' => :destroy
  end

  controller :subgenres do
    get '/getsubgenres' => :getsubgenres
  end

  controller :play do
    post "/play" => :index
    get '/play' => :gotohomepage
    get "/updateattempt" => :updateattempt
    get "/getquestion" => :getquestion
    get "/leader" => :leaderboard
    get "/adminleader" => "attempts#leaderboard"
    get "/loadll" => :loadll
    get "/quizstatus" => "play#quizstatus"
    get "/chart" => "play#chart"
    get "/getchart" => :getchart
  end
  
  root :to => redirect("/login")

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :set_genre, only: [:show, :edit, :update, :destroy]

  # GET /genres
  # GET /genres.json
  def index
    if session[:user_id] and User.find_by(id: session[:user_id]).name == "admin"
      @genres = Genre.all
    else
      redirect_to "422"
    end
  end

  # GET /genres/1
  # GET /genres/1.json
  def show
  end

  # GET /genres/new
  def new
    if session[:user_id] and User.find_by(id: session[:user_id]).name == "admin"
      @genre = Genre.new
    else
      redirect_to "/422"
    end
  end

  # GET /genres/1/edit
  def edit
    if session[:user_id] and User.find_by(id: session[:user_id]).name == "admin"
    else
      redirect_to "/422"
    end
  end

  # POST /genres
  # POST /genres.json
  def create
    if session[:user_id] and User.find_by(id: session[:user_id]).name == "admin"
      @genre = Genre.new(genre_params)
      respond_to do |format|
        if @genre.save
          format.html { redirect_to @genre, notice: 'Genre was successfully created.' }
          format.json { render :show, status: :created, location: @genre }
        else
          format.html { render :new }
          format.json { render json: @genre.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to "/422"
    end
  end

  # PATCH/PUT /genres/1
  # PATCH/PUT /genres/1.json
  def update
    if session[:user_id] and User.find_by(id: session[:user_id]).name == "admin"
      respond_to do |format|
        if @genre.update(genre_params)
          format.html { redirect_to @genre, notice: 'Genre was successfully updated.' }
          format.json { render :show, status: :ok, location: @genre }
        else
          format.html { render :edit }
          format.json { render json: @genre.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to "/422"
    end
  end

  # DELETE /genres/1
  # DELETE /genres/1.json
  def destroy
    if session[:user_id] and User.find_by(id: session[:user_id]).name == "admin"
      g=Genre.find(params[:id])
      if @a=Attempt.where(:sname => g.name)
        @a.destroy_all
      end
      Subgenre.where(:gname => g.name).destroy_all
      Question.where(:gname => g.name).destroy_all
      @genre.destroy
      respond_to do |format|
        format.html { redirect_to genres_url, notice: 'Genre was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      redirect_to "/422"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_genre
      @genre = Genre.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def genre_params
      params.require(:genre).permit(:name)
    end
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/genres/_form.html.erb
<%= form_with(model: genre, local: true) do |form| %>
  <% if genre.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(genre.errors.count, "error") %> prohibited this genre from being saved:</h2>

      <ul>
      <% genre.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, class: "label"%><br>
    <%= form.text_field :name, id: :genre_name, class: "w3-input" %>
  </div>

  <div >
    &nbsp; <%= form.submit class: "w3-btn w3-teal" %>
  </div>
  <br>
<% end %>

app/views/genres/edit.html.erb
<h1>Editing Genre</h1>
<div>
&nbsp;<%= render 'form', genre: @genre ,class: "al"%>

&nbsp;<%= link_to 'Show', @genre ,class: "al"%> |
&nbsp;<%= link_to 'Back', genres_path ,class: "al"%>
</div>

app/views/genres/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Genres</h1>

<table>
  <thead>
    <tr>
      <th class="w3-table th" style="color: teal;">Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @genres.each do |genre| %>
      <tr>
        <td class="label"><%= genre.name %></td>
        <td><%= link_to 'Show', genre,class: "al" %></td>
        <td><%= link_to 'Edit', edit_genre_path(genre) ,class: "al"%></td>
        <td><%= link_to 'Destroy', genre, method: :delete,class: "al", data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

&nbsp;<%= link_to 'New Genre', new_genre_path,class: "al" %> |
&nbsp;<%= link_to 'Home', admin_url ,class: "al"%> |
&nbsp;<%= link_to 'logout', logout_url,class: "al" %><br>

app/views/genres/new.html.erb
<h1>New Genre</h1>

<%= render 'form', genre: @genre %>

&nbsp;<%= link_to 'Home', admin_url ,class: "al"%> |
&nbsp;<%= link_to 'logout', logout_url ,class: "al"%><br>

app/views/genres/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  &nbsp;<strong class="label">Name:  &nbsp;<%= @genre.name %></strong> 
</p>

&nbsp;<%= link_to 'Edit', edit_genre_path(@genre),class: "al" %> |
&nbsp;<%= link_to 'Back', genres_path,class: "al" %> |
&nbsp;<%= link_to 'Home', admin_url ,class: "al"%> |
&nbsp;<%= link_to 'logout', logout_url ,class: "al"%><br>