config/routes.rb
Rails.application.routes.draw do
  resources :attempts
  resources :subgenres
  resources :questions
  resources :genres
  resources :destroys
  resources :users 
 # get 'admin/index'

  #get 'sessions/new'
  #root 'welcome#index'
  get 'sessions/create'

  get 'sessions/destroy'

  

  get 'admin' => 'admin#index'

  get 'homepage' => 'play#homepage'

  controller :sessions do
  	get 'login' => :new
  	post 'login' => :create
  	get 'logout' => :destroy
  end

  controller :subgenres do
    get '/getsubgenres' => :getsubgenres
  end

  controller :play do
    post "/play" => :index
    get '/play' => :gotohomepage
    get "/updateattempt" => :updateattempt
    get "/getquestion" => :getquestion
    get "/leader" => :leaderboard
    get "/adminleader" => "attempts#leaderboard"
    get "/loadll" => :loadll
    get "/quizstatus" => "play#quizstatus"
    get "/chart" => "play#chart"
    get "/getchart" => :getchart
  end
  
  root :to => redirect("/login")

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/question.rb
class Question < ApplicationRecord
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    if session[:user_id] and User.find_by(id: session[:user_id]).name == "admin"
      @questions = Question.all
    else
      redirect_to "/422"
    end
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    if session[:user_id] and User.find_by(id: session[:user_id]).name == "admin"
      @question = Question.new
    else
      redirect_to "/422"
    end
  end

  # GET /questions/1/edit
  def edit
    if session[:user_id] and User.find_by(id: session[:user_id]).name == "admin"
    else
      redirect_to "/422"
    end
  end

  # POST /questions
  # POST /questions.json
  def create
    if session[:user_id] and User.find_by(id: session[:user_id]).name == "admin"
      ques=params[:question]
      if Subgenre.find_by(name: ques[:sname] , gname: ques[:gname])
        @question = Question.new(question_params)
        respond_to do |format|
          if @question.save
            format.html { redirect_to @question, notice: 'Question was successfully created.' }
            format.json { render :show, status: :created, location: @question }
          else
            format.html { render :new }
            format.json { render json: @question.errors, status: :unprocessable_entity }
          end
        end
      else
        redirect_to "/questions/new", notice: "Please select appropriate Subgenre"
      end
    else
      redirect_to "/422"
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    if session[:user_id] and User.find_by(id: session[:user_id]).name == "admin"
      respond_to do |format|
        if @question.update(question_params)
          format.html { redirect_to @question, notice: 'Question was successfully updated.' }
          format.json { render :show, status: :ok, location: @question }
        else
          format.html { render :edit }
          format.json { render json: @question.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to "/422"
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    if session[:user_id] and User.find_by(id: session[:user_id]).name == "admin"
      @question.destroy
      respond_to do |format|
        format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      redirect_to "/422"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:question, :option1, :option2, :option3, :option4, :answer, :gname, :sname)
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_with(model: question, local: true) do |form| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :question, class: "label"%>
   <%= form.text_field :question, id: :question_question, class: "w3-input" ,style: "width:50%;"%>
  </div>

  <div class="field">
  <%= form.label :option1, class: "label" %>
    <%= form.text_field :option1, id: :question_option1, class: "w3-input"%>
  </div>

  <div class="field">
    <%= form.label :option2, class: "label" %>
    <%= form.text_field :option2, id: :question_option2, class: "w3-input" %>
  </div>

  <div class="field">
    <%= form.label :option3, class: "label" %>
    <%= form.text_field :option3, id: :question_option3, class: "w3-input" %>
  </div>

  <div class="field">
    <%= form.label :option4, class: "label" %>
    <%= form.text_field :option4, id: :question_option4, class: "w3-input" %>
  </div>

  <div class="field">
    <%= form.label :answer, class: "label" %>
    <%= form.text_field :answer, id: :question_answer, class: "w3-input" %>
  </div>

  <div class="field" onchange="fillsgenre()">
    <%= form.label :gname, class: "label"  %>
    &nbsp;<%= form.collection_select :gname, Genre.all, :name, :name, {prompt: true},{id: "questions_gname"} %>  
  </div>


  <div class="field" id="sgenrenames">
  &nbsp;<%= form.label :sname , class: "label"%>
  &nbsp;<%= form.select :sname, options_for_select([]),{prompt: "Select Subgenre"},{id:"subgenre_list"}%>
  </div> 
 <br>
  <div class="actions">
    &nbsp;<%= form.submit class: "w3-btn w3-teal"%>
  </div>
  <br>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Show', @question,class: "al" %> |
<%= link_to 'Back', questions_path,class: "al" %> |
&nbsp;<%= link_to 'Home', admin_url,class: "al" %> |
&nbsp;<%= link_to 'logout', logout_url,class: "al" %><br>

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Questions</h1>

<table>
  <thead>
    <tr>
      <th class="w3-table th" style="color: teal;">Question</th>
      <th style="color: teal;">Option1</th>
      <th style="color: teal;">Option2</th>
      <th style="color: teal;">Option3</th>
      <th style="color: teal;">Option4</th>
      <th style="color: teal;">Answer</th>
      <th style="color: teal;">Gname</th>
      <th style="color: teal;">Sname</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td class="label"><%= question.question %></td>
        <td class="label"><%= question.option1 %></td>
        <td class="label"><%= question.option2 %></td>
        <td class="label"><%= question.option3 %></td>
        <td class="label"><%= question.option4 %></td>
        <td class="label"><%= question.answer %></td>
        <td class="label"><%= question.gname %></td>
        <td class="label"><%= question.sname %></td>
        <td ><%= link_to 'Show', question ,class: "al"%></td>
        <td><%= link_to 'Edit', edit_question_path(question) ,class: "al"%></td>
        <td><%= link_to 'Destroy', question, method: :delete,class: "al", data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_question_path,class: "al" %> |
&nbsp;<%= link_to 'Home', admin_url,class: "al" %> |
&nbsp;<%= link_to 'logout', logout_url,class: "al" %><br>

app/views/questions/new.html.erb
<% if flash[:notice] %>
	<p id="notice"><%= flash[:notice]%></p>
<% end %>
<h1>New Question</h1>

<%= render 'form', question: @question %>

&nbsp;<%= link_to 'Back', questions_path,class: "al" %> |
&nbsp;<%= link_to 'Home', admin_url ,class: "al"%> |
&nbsp;<%= link_to 'logout', logout_url ,class: "al"%><br>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Question:</strong>
  <%= @question.question %>
</p>

<p>
  <strong>Option1:</strong>
  <%= @question.option1 %>
</p>

<p>
  <strong>Option2:</strong>
  <%= @question.option2 %>
</p>

<p>
  <strong>Option3:</strong>
  <%= @question.option3 %>
</p>

<p>
  <strong>Option4:</strong>
  <%= @question.option4 %>
</p>

<p>
  <strong>Answer:</strong>
  <%= @question.answer %>
</p>

<p>
  <strong>Gname:</strong>
  <%= @question.gname %>
</p>

<p>
  <strong>Sname:</strong>
  <%= @question.sname %>
</p>

<%= link_to 'Edit', edit_question_path(@question) ,class: "al"%> |
<%= link_to 'Back', questions_path ,class: "al"%> |
&nbsp;<%= link_to 'Home', admin_url ,class: "al"%> |
&nbsp;<%= link_to 'logout', logout_url ,class: "al"%><br>