config/routes.rb
Rails.application.routes.draw do
  resources :attempts
  resources :subgenres
  resources :questions
  resources :genres
  resources :destroys
  resources :users 
 # get 'admin/index'

  #get 'sessions/new'
  #root 'welcome#index'
  get 'sessions/create'

  get 'sessions/destroy'

  

  get 'admin' => 'admin#index'

  get 'homepage' => 'play#homepage'

  controller :sessions do
  	get 'login' => :new
  	post 'login' => :create
  	get 'logout' => :destroy
  end

  controller :subgenres do
    get '/getsubgenres' => :getsubgenres
  end

  controller :play do
    post "/play" => :index
    get '/play' => :gotohomepage
    get "/updateattempt" => :updateattempt
    get "/getquestion" => :getquestion
    get "/leader" => :leaderboard
    get "/adminleader" => "attempts#leaderboard"
    get "/loadll" => :loadll
    get "/quizstatus" => "play#quizstatus"
    get "/chart" => "play#chart"
    get "/getchart" => :getchart
  end
  
  root :to => redirect("/login")

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  validates	:name, uniqueness: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_action :authorize, only: [:new, :create, :index]
  
  def index
    if session[:user_id] and User.find_by(id: session[:user_id]).name == "admin"
      @users = User.all
    else
      redirect_to "/422"
    end
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to login_url, notice: 'User was successfully created.Please Login Now' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to admin_url, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if session[:user_id] and User.find_by(id: session[:user_id]).name == "admin"
      if @user.name !="admin"
        if @a=Attempt.where(:uname => @user.name)
          @a.destroy_all
        end
        @user.destroy
        respond_to do |format|
          format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
          format.json { head :no_content }
        end
      else
        redirect_to users_url, notice: "Cannot destroy admin account"
      end
    else
      redirect_to "/422"
    end
  end
  
  
  private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <table >
  <tr>
    <td><%= form.label :name, class: "label"%></td>
  <tr>  <td><%= form.text_field :name, id: :user_name, class: "w3-input"%></td></tr>
  </tr>

  <tr class="field">
    <td><%= form.label :password , class: "label"%></td>
    <tr><td><%= form.password_field :password, id: :user_password, class: "w3-input" %></td></tr>
  </tr>

  <tr class="field">
    <td><%= form.label :password_confirmation , class: "label"%></td>
    <tr><td><%= form.password_field :password_confirmation, id: :user_password_confirmation, class: "w3-input" %></td></tr>
  </tr>
  <tr class="actions" style="margin-top: 5px ">
    <td><%= form.submit class: "w3-btn w3-teal"%></td>
  </tr>
  </table>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>
<%= link_to 'Show', @user,class: "al" %> |
<%= link_to 'Back', users_path,class: "al" %>

app/views/users/index.html.erb
<h1>Users</h1>
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>
<table>
  <thead>
    <tr>
      <th class="w3-table th" style="color: teal;">Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td class="label" style="text-align: center; "><%= user.name %></td>
        <td><%= link_to 'Show', user,class: "al" %></td>
        <td><%= link_to 'Edit', edit_user_path(user),class: "al" %></td>
        <td><%= link_to 'Destroy', user, method: :delete,class: "al", data: { confirm: 'Are you sure?' } %></td>
      </tr>
      
    <% end %>
  </tbody>
</table>
<br>
&nbsp;<%= link_to 'New User', new_user_path,class: "al" %> |
&nbsp;<%= link_to 'Home', admin_url,class: "al" %> |
&nbsp;<%= link_to 'logout', logout_url,class: "al" %><br>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>
<br>
&nbsp;<%= link_to 'Login', login_url,class: "al" %> 

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  &nbsp;<strong class="label">Name: &nbsp; <%= @user.name %></strong>
  
</p>

<%= link_to 'Edit', edit_user_path(@user),class: "al" %> |
<%= link_to 'Back', users_path ,class: "al"%> |
&nbsp;<%= link_to 'Home', admin_url ,class: "al"%> |
&nbsp;<%= link_to 'logout', logout_url ,class: "al"%><br>