config/routes.rb
Rails.application.routes.draw do
  resources :attempts
  resources :subgenres
  resources :questions
  resources :genres
  resources :destroys
  resources :users 
 # get 'admin/index'

  #get 'sessions/new'
  #root 'welcome#index'
  get 'sessions/create'

  get 'sessions/destroy'

  

  get 'admin' => 'admin#index'

  get 'homepage' => 'play#homepage'

  controller :sessions do
  	get 'login' => :new
  	post 'login' => :create
  	get 'logout' => :destroy
  end

  controller :subgenres do
    get '/getsubgenres' => :getsubgenres
  end

  controller :play do
    post "/play" => :index
    get '/play' => :gotohomepage
    get "/updateattempt" => :updateattempt
    get "/getquestion" => :getquestion
    get "/leader" => :leaderboard
    get "/adminleader" => "attempts#leaderboard"
    get "/loadll" => :loadll
    get "/quizstatus" => "play#quizstatus"
    get "/chart" => "play#chart"
    get "/getchart" => :getchart
  end
  
  root :to => redirect("/login")

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/subgenre.rb
class Subgenre < ApplicationRecord
end

app/controllers/subgenres_controller.rb
class SubgenresController < ApplicationController
  before_action :set_subgenre, only: [:show, :edit, :update, :destroy]

  # GET /subgenres
  # GET /subgenres.json
  def index
    if session[:user_id] and User.find_by(id: session[:user_id]).name == "admin"
      @subgenres = Subgenre.all
    else
      redirect_to "/422"
    end
  end

  # GET /subgenres/1
  # GET /subgenres/1.json
  def show
  end

  # GET /subgenres/new
  def new
    if session[:user_id] and User.find_by(id: session[:user_id]).name == "admin"
      @subgenre = Subgenre.new
    else
      redirect_to "/422"
    end
  end

  # GET /subgenres/1/edit
  def edit
    if session[:user_id] and User.find_by(id: session[:user_id]).name == "admin"
    else
      redirect_to "/422"
    end
  end

  def getsubgenres
    render json: Subgenre.where(:gname => params[:genre_name])
  end
  # POST /subgenres
  # POST /subgenres.json
  def create
    if session[:user_id] and User.find_by(id: session[:user_id]).name == "admin"
      @subgenre = Subgenre.new(subgenre_params)

      respond_to do |format|
        if @subgenre.save
          format.html { redirect_to @subgenre, notice: 'Subgenre was successfully created.' }
          format.json { render :show, status: :created, location: @subgenre }
        else
          format.html { render :new }
          format.json { render json: @subgenre.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to "/422"
    end
  end

  # PATCH/PUT /subgenres/1
  # PATCH/PUT /subgenres/1.json
  def update
    if session[:user_id] and User.find_by(id: session[:user_id]).name == "admin"
      respond_to do |format|
        if @subgenre.update(subgenre_params)
          format.html { redirect_to @subgenre, notice: 'Subgenre was successfully updated.' }
          format.json { render :show, status: :ok, location: @subgenre }
        else
          format.html { render :edit }
          format.json { render json: @subgenre.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to "/422"
    end
  end

  # DELETE /subgenres/1
  # DELETE /subgenres/1.json
  def destroy
    if session[:user_id] and User.find_by(id: session[:user_id]).name == "admin"
      sgenre=Subgenre.find(params[:id])
      if @a=Attempt.where(:sname => sgenre.name)
        @a.destroy_all
      end
      Question.where(:sname => sgenre.name).destroy_all
      @subgenre.destroy
      respond_to do |format|
        format.html { redirect_to subgenres_url, notice: 'Subgenre was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      redirect_to "/422"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subgenre
      @subgenre = Subgenre.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subgenre_params
      params.require(:subgenre).permit(:name, :gname)
    end
end

app/helpers/subgenres_helper.rb
module SubgenresHelper
end

app/views/subgenres/_form.html.erb
<%= form_with(model: subgenre, local: true) do |form| %>
  <% if subgenre.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(subgenre.errors.count, "error") %> prohibited this subgenre from being saved:</h2>

      <ul>
      <% subgenre.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, class: "label"%>
    <%= form.text_field :name, id: :subgenre_name ,class: "w3-input"%>
  </div>

  <div class="field">
    <%= form.label :gname, class: "label" %><br>
    &nbsp;<%= form.collection_select :gname, Genre.all, :name, :name, prompt: true %>
  </div>
  <br>
  <div class="actions">
    &nbsp;<%= form.submit class: "w3-btn w3-teal"%>
  </div>
<% end %>

app/views/subgenres/edit.html.erb
<h1>Editing Subgenre</h1>

<%= render 'form', subgenre: @subgenre %>

&nbsp;<%= link_to 'Show', @subgenre,class: "al" %> |
&nbsp;<%= link_to 'Back', subgenres_path,class: "al" %> |
&nbsp;<%= link_to 'Home', admin_url,class: "al" %> |
&nbsp;<%= link_to 'logout', logout_url,class: "al" %><br>

app/views/subgenres/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Subgenres</h1>

<table>
  <thead>
    <tr>
      <th class="w3-table th" style="color: teal;">Name</th>
      <th >Gname</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subgenres.each do |subgenre| %>
      <tr>
        <td class="label"><%= subgenre.name %></td>
        <td class="label"><%= subgenre.gname %></td>
        <td><%= link_to 'Show', subgenre,class: "al" %></td>
        <td><%= link_to 'Edit', edit_subgenre_path(subgenre),class: "al" %></td>
        <td><%= link_to 'Destroy', subgenre, method: :delete,class: "al", data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

&nbsp;<%= link_to 'New Subgenre', new_subgenre_path,class: "al" %> |
&nbsp;<%= link_to 'Home', admin_url,class: "al" %> |
&nbsp;<%= link_to 'logout', logout_url,class: "al" %><br>

app/views/subgenres/new.html.erb
<h1>New Subgenre</h1>

<%= render 'form', subgenre: @subgenre %>
<br>
&nbsp;<%= link_to 'Back', subgenres_path,class: "al" %> |
&nbsp;<%= link_to 'Home', admin_url ,class: "al"%> |
&nbsp;<%= link_to 'logout', logout_url,class: "al" %><br>

app/views/subgenres/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong class="label">Name: &nbsp;<%= @subgenre.name %></strong>
</p>
<p>
  <strong class="label">Gname: &nbsp;<%= @subgenre.gname %></strong>
  
</p>
&nbsp;<%= link_to 'Edit', edit_subgenre_path(@subgenre),class: "al" %> |
&nbsp;<%= link_to 'Back', subgenres_path,class: "al" %> |
&nbsp;<%= link_to 'Home', admin_url,class: "al" %> |
&nbsp;<%= link_to 'logout', logout_url,class: "al" %><br>